config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

  resources :users, only: [:new, :create, :edit] do
    collection do
      post :signin
      delete :signout
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user

    mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:create, :destroy]

  def index
    # @posts = Post.all
    @posts = Post.order(created_at: :desc)
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
      params.require(:post).permit(:body, :picture).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        user = User.new(user_params)
        user.save
        redirect_to root_path
    end

    def edit
       @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        # redirect_to root_path
        redirect_to "/posts/#{@post.id}"
    end

    def signin
        login(params[:email], params[:password])
        redirect_to root_path
    end

    def signout
        logout
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tubuyaki</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>

<header>
  <h1><a href="/"><i class="fa fa-users" aria-hidden="true"></i></a></h1>
  <h2>「いま」起きていることを見つけよう。<br>
Webの事からプログラムの事まで、みんなの話題がわかる。</h2>
</header>

<div class="container">
    <div class="row">
    <!-- <div id="sub"> -->
    <div class="col-md-4">
        <% if logged_in? %>
        <%= image_tag current_user.icon, width: 80, height: 80 %>
        <%= current_user.name %>でログイン中
        <p>
            <div class="button3"><%= link_to 'ログアウト', signout_users_path, method: :delete %></div>
            <% else %>
            <div id="login_form">
                <%= form_tag signin_users_path, class: 'user_form' do %>
                <label for="email">メールアドレス:</label> <%= text_field_tag :email %><br><br>
                <label for="password">パスワード:</label>　　<%= password_field_tag :password %><br>
                <div class="button2"><%= submit_tag 'ログイン' %></div>
                <% end %>
                <div class="button3"><%= link_to '新規登録', new_user_path %></div>
            </div>
            <% end %>
        </div>


    <%= yield %>
    </div>
</div>

<p class="pagetop"><a href="#wrap"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></p>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<div class="formArea">
    <%= f.text_area :body %>
    <p style="margin:20px;">
        <%= f.file_field :picture %>
    </p>
</div>
<div class="button1"><%= f.submit '投 稿' %></div>
<% end %>

app/views/posts/index.html.erb
<div class="main">
<div class="col-md-8">
<% if logged_in? %>
    <%= render 'form' %>
<% end %>

<!-- <h2>投稿一覧</h2> -->
<div id="top">
<table>
    <% @posts.each do |post| %>
    <tr>
        <td class="icon">
            <%= image_tag post.user.icon, width: 50, height: 50 %><br>
            「<%= post.user.name %>」
        </td>
        <!-- <td class="name">「<%= post.user.name %>」</td> -->
        <td class="body">
            <%= image_tag(post.picture_url, width:380) if post.picture.present? %><br>
            <p><%= post.body %></p>
        </td>
    </tr>
    <tr>
        <% if logged_in? && current_user == post.user %>
<!--             <td><%#= link_to post_path(post), method: :delete  do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <%# end %>
            </td> -->
            <td colspan="3" class="trash">
                <%= link_to(content_tag(:i, '', class: 'fa fa-trash-o'), post_path(post), :method => :delete) %>
            </td>
        <% end %>
    </tr>
    <% end %>
</table>
</div>
</div>

app/views/users/_form.html.erb
<div id="user">
<%= link_to '投稿一覧へ', posts_path %><br /><br />

<%= form_for @user, class: 'user_form' do |f| %>
<table>
<tr>
    <td class="label">名前:</td>
    <td class="field"><%= f.text_field :name, class: 'box1' %></td>
</tr>

<tr>
    <td class="label">メールアドレス:</td>
    <td><%= f.text_field :email, class: 'box1' %></td>
</tr>

<tr>
    <td class="label">パスワード:</td>
    <td><%= f.password_field :password, class: 'box1' %></td>
</tr>

<tr>
    <td class="label">アイコン画像:</td>
    <td><%= f.text_field :icon, class: 'box1' %></td>
</tr>

</table>

  <div class="button2"><%= f.submit 'ユーザ登録' %></div>
<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<%= link_to '投稿一覧へ', posts_path %><br /><br />

<%= form_for @user, class: 'user_form' do |f| %>
  <label for="name">name:</label> <%= f.text_field :name %><br />
  <label for="email">email:</label> <%= f.text_field :email %><br />
  <label for="password">password:</label> <%= f.password_field :password %><br />
  <label for="icon">icon:</label> <%= f.text_field :icon %><br />
  <div class="actions"><%= f.submit 'ユーザ登録' %></div>
<% end %>